### ISSUE TITLE
Errors are swallowed

### ISSUE THREAD

**Issue by sgtlambda** [ExodusMovement/redux-watch#6]
If an error is thrown inside the diff handler, e.g.

```js
let watcher = watch(store.getState, 'auth.token');

store.subscribe(watcher(token => {

    throw new Error('something goes wrong here');
}));
```

The error never shows up in the console log. In my case, it took me a while to debug as the application hung for what seemed to be no reason whatsoever. If I replace the above code, in the same context,  with

```js
store.subscribe(token => {

    throw new Error('something goes wrong here');
});
```

It does show up.

**Comment by fanatid** [comment]
@sgtlambda are you sure that `auth.token` was changed?
```js
const redux = require('redux')
const rw = require('redux-watch')

const fnErrorThrow = () => { throw new Error('redux-watch!') }

const store = redux.createStore((state, action) => {
  if (action.type === 'test') state.x = Math.random()
  return state
}, {})
// store.subscribe(fnErrorThrow)
store.subscribe(rw(store.getState, 'x')(fnErrorThrow))
store.dispatch({ type: 'test' })
```

output:
```
$ node t.js 
/home/kirill/tmp/t.js:4
const fnErrorThrow = () => { throw new Error('redux-watch!') }
                             ^

Error: redux-watch!
    at fnErrorThrow (/home/kirill/tmp/t.js:4:36)
    at Array.<anonymous> (/home/kirill/tmp/node_modules/redux-watch/index.js:17:9)
    at Object.dispatch (/home/kirill/tmp/node_modules/redux/lib/createStore.js:186:19)
    at Object.<anonymous> (/home/kirill/tmp/t.js:12:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by sgtlambda** [comment]
I dug in using devtools' `break on all (caught) exceptions`, turns out the problem wasn't caused by `redux-watch` but rather by a piece of middleware that was emitting errors as redux actions and as such, swallowing them :) Thank you for your time!
